### PR TITLE
[db,scan,jsonapi] bug fix to handle date_released before 1970

### LINKED ISSUE #1555: Date seems off
I noticed that on the music tab, some albums added to Owntone had wrong dates. When I examine the files in other tools, the date is correct.

Screenshot 2022-12-09 at 1 27 43 PM

Input #0, flac, from '01-O Come All Ye Faithful.flac':
  Metadata:
    TITLE           : O Come All Ye Faithful
    ARTIST          : Bobby Darin
    ALBUM           : The 25th Day of December with Bobby Darin
    album_artist    : Bobby Darin
    comment         : Give Darin credit for choosing mostly American spirituals for this release, but he would have fallen flat on his back had he not been backed by the Bobby Scott Chorale on "Go Tell it on the Mountain," "Jehovah Hallelujah," and other rousing numbers. On th
                    : <br />&copy  Dennis MacDonald /TiVo
    GENRE           : Christmas
    COPYRIGHT       : © 1960 Atlantic Recording Corp For the United States and WEA International Inc. for the world outside of the United States. ℗ 1960 Atlantic Recording Corp For the United States and WEA International Inc. for the world outside of the United States.
    track           : 01
    disc            : 1/1
    TRACKTOTAL      : 14
    DISCTOTAL       : 01
    DATE            : 1960-10-01
  Duration: 00:02:22.31, start: 0.000000, bitrate: 580 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
  Stream #0:1: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 600x600 [SAR 100:100 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)

Owntone 28.5, Debian 11.5

I did try a full metadata rescan without change.

### PR DESCRIPTION
**Pull request by whatdoineed2do**
Closes #1555

Release date of track is assumed to be >1970 and stored/handled as an `uint32_t` which causes mishandling of dates before unix epoch.  For example, a file with release date of `1960-10-04`, the db stores `date_released` as `4003280896` vs `-291686400` and gets misidenfied as a date in 2096.

I've bumped the storage and handling of `struct media_file_info::date_released` to `int64` since there's a note for all ints to be handled as unsigned. 

Test before and after through json api  (see `date_released`):
* master
```
{
  "id": 47,
  "title": "old song",
  "title_sort": "old song",
  "artist": "foobar",
  "artist_sort": "foobar",
  "album": "nothing good",
  "album_sort": "nothing good",
  "album_id": "2347841309122213946",
  "album_artist": "foobar",
  "album_artist_sort": "foobar",
  "album_artist_id": "7097352992947437494",
  "genre": "Pop",
  "year": 1960,
  "track_number": 1,
  "disc_number": 0,
  "length_ms": 10031,
  "rating": 0,
  "play_count": 0,
  "skip_count": 0,
  "time_added": "2022-12-11T15:51:16Z",
  "date_released": "2096-11-09",
  "seek_ms": 0,
  "type": "mp3",
  "samplerate": 44100,
  "bitrate": 128,
  "channels": 2,
  "usermark": 0,
  "media_kind": "music",
  "data_kind": "file",
  "path": "/home/ray/Music/date1960.mp3",
  "uri": "library:track:47",
  "artwork_url": "/artwork/item/47"
}
```
* after fix
```
{
  "id": 47,
  "title": "old song",
  "title_sort": "old song",
  "artist": "foobar",
  "artist_sort": "foobar",
  "album": "nothing good",
  "album_sort": "nothing good",
  "album_id": "2347841309122213946",
  "album_artist": "foobar",
  "album_artist_sort": "foobar",
  "album_artist_id": "7097352992947437494",
  "genre": "Pop",
  "year": 1960,
  "track_number": 1,
  "disc_number": 0,
  "length_ms": 10031,
  "rating": 0,
  "play_count": 0,
  "skip_count": 0,
  "time_added": "2022-12-11T15:51:16Z",
  "date_released": "1960-10-04",
  "seek_ms": 0,
  "type": "mp3",
  "samplerate": 44100,
  "bitrate": 128,
  "channels": 2,
  "usermark": 0,
  "media_kind": "music",
  "data_kind": "file",
  "path": "/home/ray/Music/date1960.mp3",
  "uri": "library:track:47",
  "artwork_url": "/artwork/item/47"
}
```

### CODE REVIEW

File: src/library/filescanner_ffmpeg.c [hunk 1]
```diff
@@ -111,7 +112,7 @@ parse_date(struct media_file_info *mfi, char *date_string)
        || strptime(date_string, "%F", &tm)
      )
     {
-      *date_released = (uint32_t)mktime(&tm);
+      *date_released = (int32_t)mktime(&tm);
```
Comment (ejurgensen) [inline src/library/filescanner_ffmpeg.c:115]: Not quite sure why it's int32_t here? (and below)

Comment (whatdoineed2do) [reply src/library/filescanner_ffmpeg.c:115]: Do you mean why not let the compiler force the implicit conversion to the signed int64 ?

It has to be signed to deal with negative values meaning dates prior 1970.  I kept to 32bit as somehow the existing code has some assumptions that mktime needs to 32bit. Maybe an oversight on my part and we don't need the explo cast

Comment (whatdoineed2do) [reply src/library/filescanner_ffmpeg.c]: drop cast since its redundant

Comment (ejurgensen) [reply src/library/filescanner_ffmpeg.c]: C's integer rules always confuse me, but I'm thinking that since mktime returns time_t and you want to store it as int64 a cast to int64 would be needed?

Comment (whatdoineed2do) [reply src/library/filescanner_ffmpeg.c]: This has always been my understanding, aklthough without the correct terminology i'm can't find the right reference online

_promotion_ rules will take care of assignment of smaller (say 32bit `time_t`) RHS to larger (64bit) LHS, no cast needed since LHS is _wider_.  If both LHS / RHS are same size but different sign-ness then result is on bitwise representation of LHS destination.

 i can add explicit cast to `int64_t` in the assigment but the assignment to `int64` should be enough

**Comment by ejurgensen** [comment]
Doing without the cast sounds fine, so merged it now, thanks for the pr.
