### PR TITLE
[db] fix 'add next' when in queue shuffle mode

### LINKED ISSUE #1382: "Add Next" doesn't work on shuffled queue
When I'm listening to a queue of songs, and then search for a specific song, find it and click the vertical ... the options appear to Add or "Add Next". Choosing "Add Next" puts the song into the queue in a seemingly random spot (in my case, up with the previously played songs) and not after the currently playing song.

### PR DESCRIPTION
**Pull request by whatdoineed2do**
Fixes #1382

### CODE REVIEW

File: src/db.c [hunk 1]
```diff
@@ -5234,7 +5243,7 @@ db_queue_add_by_query(struct query_params *qp, char reshuffle, uint32_t item_id,
     goto end_transaction;
 
   // Reshuffle after adding new items
-  if (reshuffle)
+  if (position == -1 && reshuffle)
```
Comment (chme) [inline src/db.c:5246]: It would be better to have the same condition as in line 5193. We modify the `queue_count` value, so cannot use it here. Maybe best to introduce a variable that stores the condition result. And extend the existing comment to explain a bit why we do not always reshuffle, even when the parameter shuffle is true.

```
  bool append_to_queue;

  ...

  append_to_queue = (position < 0 || position > queue_count);

  if (append_to_queue)
    {
      pos = queue_count;
      ...
    }
  else
    {
      pos = position;
      ...
    }

  // Reshuffle after adding new items, if no queue position was specified
  if (append_to_queue && reshuffle)
    {
      ret = queue_reshuffle(item_id, queue_version);
    }
```

Comment (whatdoineed2do) [reply src/db.c]: thanks - updated to match review

**Comment by chme** [comment]
Great, thanks!
